/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.sigmas.presentacion;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;
import pe.sigmas.entity.*;
import pe.sigmas.logica.*;
import pe.sigmas.util.Generic;
import pe.sigmas.util.*;

/**
 *
 * @author Elle Lawliet
 */
public class frmAdministrarUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmAdministrarUsuarios
     */
    GenericTableModel modeloTabla;
    TableColumnModel modeloColumna;
    String[] columnanes = {"ID", "CODIGO", "NUM DOCUMENTO", "RAZON SOCIAL", "CATEGORIA", "SEXO"};
    boolean[] editable = {false, false, false, false, false, false};
    boolean[] columnCheck = {false, false, false, false, false, false};
    boolean nuevo = true;

    HashMap<String, maetipopersonaBean> mapaPersona;
    HashMap<String, maesexoBean> mapaSexo;
    HashMap<String, maetipodocumentoBean> mapaDocumento;
    HashMap<String, maecategoriaBean> mapaCategoria;

    public frmAdministrarUsuarios() {
        initComponents();
        mapaPersona = new HashMap<>();
        mapaSexo = new HashMap<>();
        mapaDocumento = new HashMap<>();
        mapaCategoria = new HashMap<>();

        modeloTabla = new GenericTableModel(columnanes, columnCheck, editable);
        jTable1.setModel(modeloTabla);
        modeloColumna = jTable1.getColumnModel();
        try {
            cargarCombo();
            iniciarGrilla(6);
            ajustarColumna();
            estiloTabla();
            hideColumnTable();
            activarBotones(true, true, true, false, false);
            activarCampos(true, false);
        } catch (Exception ex) {
            Logger.getLogger(frmAdministrarUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tipoPersona = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        sexo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        tipoDocumento = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        NumDocumento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        categoria = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        CodigoUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        apepaterno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        apematerno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        observacion = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        busquedanombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("ADMINISTRACION DE USUARIOS SIGMASS");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Mantenimiento del Cliente/Usuario"));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel2Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel2.setLayout(jPanel2Layout);

        jLabel1.setText("Tipo Persona");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 8, 1, 0);
        jPanel2.add(jLabel1, gridBagConstraints);

        tipoPersona.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 0, 1, 0);
        jPanel2.add(tipoPersona, gridBagConstraints);

        jLabel2.setText("Sexo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 8, 1, 0);
        jPanel2.add(jLabel2, gridBagConstraints);

        sexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 114;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 2, 1, 41);
        jPanel2.add(sexo, gridBagConstraints);

        jLabel3.setText("Tipo Documento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 8, 1, 0);
        jPanel2.add(jLabel3, gridBagConstraints);

        tipoDocumento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 1, 0);
        jPanel2.add(tipoDocumento, gridBagConstraints);

        jLabel4.setText("Numero Documento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 8, 1, 0);
        jPanel2.add(jLabel4, gridBagConstraints);

        NumDocumento.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 172;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 2, 1, 41);
        jPanel2.add(NumDocumento, gridBagConstraints);

        jLabel5.setText("Categoria");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 8, 1, 0);
        jPanel2.add(jLabel5, gridBagConstraints);

        categoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 0, 1, 0);
        jPanel2.add(categoria, gridBagConstraints);

        jLabel6.setText("Codigo Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 8, 1, 0);
        jPanel2.add(jLabel6, gridBagConstraints);

        CodigoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CodigoUsuarioKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 172;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 2, 1, 41);
        jPanel2.add(CodigoUsuario, gridBagConstraints);

        jLabel7.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 8, 1, 0);
        jPanel2.add(jLabel7, gridBagConstraints);

        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 113;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 1, 0);
        jPanel2.add(nombre, gridBagConstraints);

        jLabel8.setText("Apellido Paterno");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 8, 1, 0);
        jPanel2.add(jLabel8, gridBagConstraints);

        apepaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apepaternoKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 172;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 2, 1, 41);
        jPanel2.add(apepaterno, gridBagConstraints);

        jLabel9.setText("Apellido Materno");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 8, 1, 0);
        jPanel2.add(jLabel9, gridBagConstraints);

        apematerno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apematernoKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 113;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 1, 0);
        jPanel2.add(apematerno, gridBagConstraints);

        jLabel10.setText("Direccion Referencial");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 8, 1, 0);
        jPanel2.add(jLabel10, gridBagConstraints);

        direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                direccionKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 368;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 2, 1, 41);
        jPanel2.add(direccion, gridBagConstraints);

        jLabel11.setText("Observacion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 8, 1, 0);
        jPanel2.add(jLabel11, gridBagConstraints);

        observacion.setColumns(20);
        observacion.setRows(5);
        observacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                observacionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(observacion);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 354;
        gridBagConstraints.ipady = 63;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 2, 34, 48);
        jPanel2.add(jScrollPane1, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Usuarios"));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Nombre"));
        jPanel4.setLayout(new java.awt.BorderLayout());

        busquedanombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busquedanombreMouseClicked(evt);
            }
        });
        busquedanombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedanombreActionPerformed(evt);
            }
        });
        busquedanombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                busquedanombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                busquedanombreKeyTyped(evt);
            }
        });
        jPanel4.add(busquedanombre, java.awt.BorderLayout.CENTER);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/sigmas/files/01_lblBuscar.png"))); // NOI18N
        jPanel4.add(jLabel12, java.awt.BorderLayout.LINE_END);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel5.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/sigmas/files/01_btnCancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/sigmas/files/01_btnModificar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/sigmas/files/01_btnSave.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/sigmas/files/01_btnEliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/sigmas/files/01_btnNuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCancelar)
                        .addComponent(btnModificar)
                        .addComponent(btnEliminar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGuardar)
                        .addComponent(btnNuevo)))
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void busquedanombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busquedanombreKeyReleased
        // TODO add your handling code here:
        if (busquedanombre.isEditable()) {
            if (evt.getKeyCode() == 40) {
                if (modeloTabla.getRowCount() > 0) {
                    jTable1.setRowSelectionInterval(0, 0);
                    jTable1.requestFocus();
                    //  mostrarDetalle(listaUnidadMedida.get(0));
                    activarBotones(true, true, true, false, false);
                }

            } else {
                try {
                    iniciarGrilla(5);
                } catch (Exception ex) {
                    Logger.getLogger(frmAdministrarUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        }
    }//GEN-LAST:event_busquedanombreKeyReleased

    private void busquedanombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busquedanombreMouseClicked
        // TODO add your handling code here:
        busquedanombre.selectAll();
    }//GEN-LAST:event_busquedanombreMouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        activarBotones(false, false, false, true, true);
        activarCampos(false, true);
        limpiarCampos();
        nuevo = true;
        tipoPersona.requestFocus();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        regpersonaBean oregpersonaBean = new regpersonaBean();
        try {
            //validar el ingreso de datos 

            oregpersonaBean.setCCodMaeSexo(((maesexoBean) sexo.getSelectedItem()).getCCodMaeSexo());
            oregpersonaBean.setCCodMaeTipoPersona(((maetipopersonaBean) tipoPersona.getSelectedItem()).getCCodMaeTipoPersona());
            oregpersonaBean.setCCodMaeEstaCivil(((maetipodocumentoBean) tipoDocumento.getSelectedItem()).getCCodMaeTipoDocumento());
            oregpersonaBean.setNvEmail(((maecategoriaBean) categoria.getSelectedItem()).getCCodMaeCategoria());
            oregpersonaBean.setNvNumDocumento(NumDocumento.getText());
            oregpersonaBean.setNvRpm(CodigoUsuario.getText());
            oregpersonaBean.setNvNombre(nombre.getText());
            oregpersonaBean.setNvApePaterno(apepaterno.getText());
            oregpersonaBean.setNvApeMaterno(apematerno.getText());
            oregpersonaBean.setNvDomiProcesal(direccion.getText());
            oregpersonaBean.setNvObservacion(observacion.getText());
            oregpersonaBean.setIIdRegUsuaRegistra(frminicio.IdUsuario);
            oregpersonaBean.setIOps(1);

            if (nuevo) {
                boolean result = Generic.getInstance(regpersonaBL.class).fnInsertarregpersonaBean(oregpersonaBean);
                if (result) {
                    JOptionPane.showInternalMessageDialog(this, "Registro correcto del Usuario", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showInternalMessageDialog(this, "Fallo al registrar el Usuario", "Mensaje", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                int index = jTable1.getSelectedRow();
                String dat = modeloTabla.getValueAt(index, 0).toString();
                oregpersonaBean.setBiIdRegPersona(Integer.parseInt(dat));

                boolean result = Generic.getInstance(regpersonaBL.class).fnActualizarregpersonaBean(oregpersonaBean);
                if (result) {
                    JOptionPane.showInternalMessageDialog(this, "Actualizacion correcta del Usuario", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showInternalMessageDialog(this, "Fallo al Actualizar el Usuario", "Mensaje", JOptionPane.ERROR_MESSAGE);
                }
            }
            activarBotones(true, false, false, false, true);
            activarCampos(true, false);
            limpiarCampos();
            busquedanombre.requestFocus();
            busquedanombre.selectAll();
            iniciarGrilla(6);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (modeloTabla.getRowCount() > 0) {
            int index = jTable1.getSelectedRow();
            if (index > -1) {
                try {
                    String dat = modeloTabla.getValueAt(index, 0).toString();

                    regpersonaBean oregpersonaBean = new regpersonaBean();
                    oregpersonaBean.setIOps(1);
                    oregpersonaBean.setBiIdRegPersona(Integer.parseInt(dat));
                    oregpersonaBean = Generic.getInstance(regpersonaBL.class).fnGetregpersonaBean(oregpersonaBean);
                    sexo.setSelectedItem(mapaSexo.get(oregpersonaBean.getCCodMaeSexo()));
                    tipoPersona.setSelectedItem(mapaPersona.get(oregpersonaBean.getCCodMaeTipoPersona()));
                    categoria.setSelectedItem(mapaCategoria.get(oregpersonaBean.getNvEmail()));
                    tipoDocumento.setSelectedItem(mapaDocumento.get(oregpersonaBean.getCCodMaeEstaCivil()));
                    NumDocumento.setText(oregpersonaBean.getNvNumDocumento());
                    CodigoUsuario.setText(oregpersonaBean.getNvTeleFijo());
                    nombre.setText(oregpersonaBean.getNvNombre());
                    apepaterno.setText(oregpersonaBean.getNvApePaterno());
                    apematerno.setText(oregpersonaBean.getNvApeMaterno());
                    direccion.setText(oregpersonaBean.getNvDomiProcesal());
                } catch (Exception ex) {
                    Logger.getLogger(frmAdministrarUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
        if ((evt.getKeyCode() == 38) || (evt.getKeyCode() == 40)) {
            activarBotones(true, true, true, false, false);
        }
    }//GEN-LAST:event_jTable1KeyReleased

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if (modeloTabla.getRowCount() > 0) {
            int index = jTable1.getSelectedRow();
            if (index > -1) {
                try {
                    String dat = modeloTabla.getValueAt(index, 0).toString();
                    regpersonaBean oregpersonaBean = new regpersonaBean();
                    oregpersonaBean.setIOps(1);
                    oregpersonaBean.setBiIdRegPersona(Integer.parseInt(dat));
                    oregpersonaBean = Generic.getInstance(regpersonaBL.class).fnGetregpersonaBean(oregpersonaBean);
                    sexo.setSelectedItem(mapaSexo.get(oregpersonaBean.getCCodMaeSexo()));
                    tipoPersona.setSelectedItem(mapaPersona.get(oregpersonaBean.getCCodMaeTipoPersona()));
                    categoria.setSelectedItem(mapaCategoria.get(oregpersonaBean.getNvEmail()));
                    tipoDocumento.setSelectedItem(mapaDocumento.get(oregpersonaBean.getCCodMaeEstaCivil()));
                    NumDocumento.setText(oregpersonaBean.getNvNumDocumento());
                    CodigoUsuario.setText(oregpersonaBean.getNvTeleFijo());
                    nombre.setText(oregpersonaBean.getNvNombre());
                    apepaterno.setText(oregpersonaBean.getNvApePaterno());
                    apematerno.setText(oregpersonaBean.getNvApeMaterno());
                    direccion.setText(oregpersonaBean.getNvDomiProcesal());
                    nuevo = false;
                    activarBotones(false, false, false, true, true);
                    activarCampos(false, true);
                } catch (Exception ex) {
                    Logger.getLogger(frmAdministrarUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (modeloTabla.getRowCount() > 0) {
            int index = jTable1.getSelectedRow();
            if (index > -1) {
                try {
                    int i = JOptionPane.showInternalConfirmDialog(this, "ESTA SEGURO DE ELIMINAR EL USUARIO", "MENSAJE", JOptionPane.OK_CANCEL_OPTION);
                    String dat = modeloTabla.getValueAt(index, 0).toString();
                    regpersonaBean oregpersonaBean = new regpersonaBean();
                    oregpersonaBean.setIIdRegUsuaRegistra(frminicio.IdUsuario);
                    oregpersonaBean.setIOps(2);
                    if (i == 0) {
                        oregpersonaBean.setBiIdRegPersona(Integer.parseInt(dat));
                        boolean result = Generic.getInstance(regpersonaBL.class).fnActualizarregpersonaBean(oregpersonaBean);
                        if (result) {
                            iniciarGrilla(6);
                            limpiarCampos();
                            activarBotones(true, true, true, false, false);
                            JOptionPane.showInternalMessageDialog(this, "Eliminacion correcta del Usuario", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            JOptionPane.showInternalMessageDialog(this, "Fallo al Eliminar el Usuario", "Mensaje", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                } catch (Exception ex) {
                    Logger.getLogger(frmAdministrarUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        activarBotones(true, true, true, false, false);
        activarCampos(true, false);
        limpiarCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void CodigoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodigoUsuarioKeyTyped
        // TODO add your handling code here:
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_CodigoUsuarioKeyTyped

    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
        // TODO add your handling code here:
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_nombreKeyTyped

    private void apepaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apepaternoKeyTyped
        // TODO add your handling code here:
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_apepaternoKeyTyped

    private void apematernoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apematernoKeyTyped
        // TODO add your handling code here:
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_apematernoKeyTyped

    private void direccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccionKeyTyped
        // TODO add your handling code here:
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_direccionKeyTyped

    private void observacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_observacionKeyTyped
        // TODO add your handling code here:
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_observacionKeyTyped

    private void busquedanombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busquedanombreKeyTyped
        // TODO add your handling code here:
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_busquedanombreKeyTyped

    private void busquedanombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedanombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busquedanombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodigoUsuario;
    private javax.swing.JTextField NumDocumento;
    private javax.swing.JTextField apematerno;
    private javax.swing.JTextField apepaterno;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JTextField busquedanombre;
    private javax.swing.JComboBox categoria;
    private javax.swing.JTextField direccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextArea observacion;
    private javax.swing.JComboBox sexo;
    private javax.swing.JComboBox tipoDocumento;
    private javax.swing.JComboBox tipoPersona;
    // End of variables declaration//GEN-END:variables

    private void iniciarGrilla(int iOps) throws Exception {
        deleteRows();
        regcontribuyenteBean oregcontribuyenteBean = new regcontribuyenteBean();
        oregcontribuyenteBean.setIOps(iOps);
        oregcontribuyenteBean.setBEstado(true);
        oregcontribuyenteBean.setNvObservacion(busquedanombre.getText());
        List lista = Generic.getInstance(regcontribuyenteBL.class).fnGridregcontribuyenteBean(oregcontribuyenteBean);

        lista.stream().forEach((list) -> {
            modeloTabla.addRow((Object[]) list);
        });
    }

    private void estiloTabla() {
        for (int i = 0; i < modeloColumna.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setHeaderRenderer(new GenericEstiloTabla());
        }
    }

    private void hideColumnTable() {
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
    }

    private void ajustarColumna() {
        modeloColumna.getColumn(0).setPreferredWidth(0);
        modeloColumna.getColumn(1).setPreferredWidth(50);
        modeloColumna.getColumn(2).setPreferredWidth(50);
        modeloColumna.getColumn(3).setPreferredWidth(200);
        modeloColumna.getColumn(4).setPreferredWidth(20);
        modeloColumna.getColumn(5).setPreferredWidth(10);
    }

    private void deleteRows() {
        while (modeloTabla.getRowCount() > 0) {
            modeloTabla.removeRow(0);
        }
    }


    private void activarBotones(boolean nuevo, boolean modificar, boolean eliminar, boolean guardar, boolean cancelar) {
        btnGuardar.setEnabled(guardar);
        btnCancelar.setEnabled(cancelar);
        btnEliminar.setEnabled(eliminar);
        btnModificar.setEnabled(modificar);
        btnNuevo.setEnabled(nuevo);
    }

    private void activarCampos(boolean izquierda, boolean derecha) {
        busquedanombre.setEditable(izquierda);
        jTable1.setEnabled(izquierda);
        NumDocumento.setEditable(derecha);
        CodigoUsuario.setEditable(derecha);
        nombre.setEditable(derecha);
        apematerno.setEditable(derecha);
        apepaterno.setEditable(derecha);
        direccion.setEditable(derecha);
        observacion.setEditable(derecha);
        tipoPersona.setEnabled(derecha);
        tipoDocumento.setEnabled(derecha);
        sexo.setEnabled(derecha);
        categoria.setEnabled(derecha);
    }

    private void limpiarCampos() {
        NumDocumento.setText("");
        CodigoUsuario.setText("");
        nombre.setText("");;
        apematerno.setText("");
        apepaterno.setText("");
        direccion.setText("");
        observacion.setText("");
        tipoPersona.setSelectedIndex(0);
        tipoDocumento.setSelectedIndex(0);
        sexo.setSelectedIndex(0);
        categoria.setSelectedIndex(0);
    }

    private void cargarCombo() throws Exception {
        tipoPersona.removeAllItems();
        sexo.removeAllItems();
        tipoDocumento.removeAllItems();
        categoria.removeAllItems();
        maetipopersonaBean omaetipopersonaBean = new maetipopersonaBean();
        maesexoBean omaesexoBean = new maesexoBean();
        maetipodocumentoBean omaetipodocumentoBean = new maetipodocumentoBean();
        maecategoriaBean omaecategoriaBean = new maecategoriaBean();
        omaetipopersonaBean.setIOps(2);
        omaesexoBean.setIOps(2);
        omaetipodocumentoBean.setIOps(2);
        omaecategoriaBean.setIOps(2);
        ArrayList<maetipopersonaBean> lista1 = Generic.getInstance(maetipopersonaBL.class).fnAutocompletemaetipopersonaBean(omaetipopersonaBean);
        ArrayList<maesexoBean> lista2 = Generic.getInstance(maesexoBL.class).fnAutocompletemaesexoBean(omaesexoBean);
        ArrayList<maetipodocumentoBean> lista3 = Generic.getInstance(maetipodocumentoBL.class).fnAutocompletemaetipodocumentoBean(omaetipodocumentoBean);
        ArrayList<maecategoriaBean> lista4 = Generic.getInstance(maecategoriaBL.class).fnAutocompletemaecategoriaBean(omaecategoriaBean);

        lista1.stream().map((v) -> {
            tipoPersona.addItem(v);
            return v;
        }).forEach((v) -> {
            mapaPersona.put(v.getCCodMaeTipoPersona(), v);
        });
        lista2.stream().map((v) -> {
            sexo.addItem(v);
            return v;
        }).forEach((v) -> {
            mapaSexo.put(v.getCCodMaeSexo(), v);
        });
        lista3.stream().map((v) -> {
            tipoDocumento.addItem(v);
            return v;
        }).forEach((v) -> {
            mapaDocumento.put(v.getCCodMaeTipoDocumento(), v);
        });
        lista4.stream().map((v) -> {
            categoria.addItem(v);
            return v;
        }).forEach((v) -> {
            mapaCategoria.put(v.getCCodMaeCategoria(), v);
        });
    }
}
