/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.sigmas.presentacion;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;
import pe.sigmas.entity.regcontribuyenteBean;
import pe.sigmas.logica.regcontribuyenteBL;
import pe.sigmas.util.Generic;
import pe.sigmas.util.GenericEstiloTabla;
import pe.sigmas.util.GenericTableModel;

/**
 *
 * @author Elle Lawliet
 */
public class frmBusquedaUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmBusquedaUsuario
     */
    GenericTableModel modeloTabla;
    TableColumnModel modeloColumna;
    String[] columnanes = {"ID", "CODIGO", "NUM DOCUMENTO", "RAZON SOCIAL", "CATEGORIA", "SEXO"};
    boolean[] editable = {false, false, false, false, false, false};
    boolean[] columnCheck = {false, false, false, false, false, false};
   // frmAdministrarValConcepto form = new frmAdministrarValConcepto();

    public frmBusquedaUsuario() {
        initComponents();
        modeloTabla = new GenericTableModel(columnanes, columnCheck, editable);
        jTable1.setModel(modeloTabla);
        modeloColumna = jTable1.getColumnModel();
        try {
            iniciarGrilla(6);
            ajustarColumna();
            estiloTabla();
            hideColumnTable();

        } catch (Exception ex) {
            Logger.getLogger(frmAdministrarUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        busquedanombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("BUSQUEDA DE USUARIOS");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Usuarios"));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Nombre"));
        jPanel4.setLayout(new java.awt.BorderLayout());

        busquedanombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busquedanombreMouseClicked(evt);
            }
        });
        busquedanombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                busquedanombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                busquedanombreKeyTyped(evt);
            }
        });
        jPanel4.add(busquedanombre, java.awt.BorderLayout.CENTER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/sigmas/files/01_lblBuscar.png"))); // NOI18N
        jPanel4.add(jLabel1, java.awt.BorderLayout.LINE_END);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel5.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void busquedanombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busquedanombreMouseClicked
        // TODO add your handling code here:
        busquedanombre.selectAll();
    }//GEN-LAST:event_busquedanombreMouseClicked

    private void busquedanombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busquedanombreKeyReleased
        // TODO add your handling code here:
        if (busquedanombre.isEditable()) {
            if (evt.getKeyCode() == 40) {
                if (modeloTabla.getRowCount() > 0) {
                    jTable1.setRowSelectionInterval(0, 0);
                    jTable1.requestFocus();
                    //  mostrarDetalle(listaUnidadMedida.get(0));                   
                }
            } else {
                try {
                    iniciarGrilla(5);
                } catch (Exception ex) {
                    Logger.getLogger(frmAdministrarUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        }
    }//GEN-LAST:event_busquedanombreKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        if (evt.getClickCount() == 2) {

            if (modeloTabla.getRowCount() > 0) {
                int index = jTable1.getSelectedRow();
                if (index > -1) {
                    try {
                        String idPersona=modeloTabla.getValueAt(index, 0).toString();
                        String codigo = modeloTabla.getValueAt(index, 1).toString();
                        String nombre = modeloTabla.getValueAt(index, 3).toString();
                        frmAdministrarValConcepto.cargarUsuario(idPersona,codigo, nombre);
                        this.dispose();
                    } catch (Exception ex) {
                        Logger.getLogger(frmAdministrarUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }

            }
            // do some action
        }


    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jTable1KeyReleased

    private void busquedanombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busquedanombreKeyTyped
        // TODO add your handling code here:
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_busquedanombreKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField busquedanombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void iniciarGrilla(int i) throws Exception {
        deleteRows();
        regcontribuyenteBean oregcontribuyenteBean = new regcontribuyenteBean();
        oregcontribuyenteBean.setIOps(i);
        oregcontribuyenteBean.setBEstado(true);
        oregcontribuyenteBean.setNvObservacion(busquedanombre.getText());
        List lista = Generic.getInstance(regcontribuyenteBL.class).fnGridregcontribuyenteBean(oregcontribuyenteBean);

        lista.stream().forEach((list) -> {
            modeloTabla.addRow((Object[]) list);
        });
    }

    private void estiloTabla() {
        for (int i = 0; i < modeloColumna.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setHeaderRenderer(new GenericEstiloTabla());
        }
    }

    private void hideColumnTable() {
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
    }

    private void ajustarColumna() {
        modeloColumna.getColumn(0).setPreferredWidth(0);
        modeloColumna.getColumn(1).setPreferredWidth(50);
        modeloColumna.getColumn(2).setPreferredWidth(50);
        modeloColumna.getColumn(3).setPreferredWidth(200);
        modeloColumna.getColumn(4).setPreferredWidth(20);
        modeloColumna.getColumn(5).setPreferredWidth(10);
    }

    private void deleteRows() {
        while (modeloTabla.getRowCount() > 0) {
            modeloTabla.removeRow(0);
        }
    }
}
