/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.sigmas.presentacion;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pe.sigmas.entity.regcontribuyenteBean;
import pe.sigmas.entity.regobligacionBean;
import pe.sigmas.entity.vencimientoBean;
import pe.sigmas.logica.regcontribuyenteBL;
import pe.sigmas.logica.regobligacionBL;
import pe.sigmas.logica.vencimientoBL;
import pe.sigmas.util.Generic;
import pe.sigmas.util.Reporte;
import pe.sigmas.util.validator;

/**
 *
 * @author Elle Lawliet
 */
public class frmEmitirReciboIndividual extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmgenerarDeudaIndividual
     */
    public frmEmitirReciboIndividual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dni = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        actual = new javax.swing.JCheckBox();
        general = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        individual = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("EMISON DE RECIBO INDIVIDUAL[DUPLICADO]");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("IMPRESION DE RECIBO POR USUARIO"));

        jLabel2.setText("DNI Contribuyente");

        jLabel3.setText("Vencimiento");

        actual.setSelected(true);
        actual.setText("Actual?");
        actual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualActionPerformed(evt);
            }
        });

        general.setText(" Enero a Deciembre?");
        general.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/sigmas/files/01_lblBuscar.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(actual)
                        .addGap(18, 18, 18)
                        .addComponent(general)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(actual)
                    .addComponent(general)))
        );

        individual.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        individual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/sigmas/files/01_btnMostrarRecibo.png"))); // NOI18N
        individual.setText("Mostrar Recibo");
        individual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                individualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(individual)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(individual)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void individualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_individualActionPerformed
        // TODO add your handling code here:
        regobligacionBean oregobligacionBean = new regobligacionBean();
        try {
            if (!dni.getText().isEmpty() && dni.getText().length() >= 8) {
                regcontribuyenteBean oregcontribuyenteBean = new regcontribuyenteBean();
                oregcontribuyenteBean.setIOps(3);
                if (!validator.validarInteger(dni.getText())) {
                    JOptionPane.showInternalMessageDialog(this, "DOCUMENTO DE IDENTIDAD INCORRECTA", "ERROR", JOptionPane.ERROR_MESSAGE);
                    dni.selectAll();
                    dni.requestFocus();
                    return;
                }
                oregcontribuyenteBean.setCCodRegContribuyente(dni.getText());
                oregcontribuyenteBean = Generic.getInstance(regcontribuyenteBL.class).fnGetregcontribuyenteBean(oregcontribuyenteBean);

                if (oregcontribuyenteBean != null) {
                    if (actual.isSelected()) {
                        Map parametros = new HashMap();
                        parametros.put("pnvCodigo", dni.getText());
                        String pathReporte = System.getProperty("user.dir") + "/src/pe/sigmas/reporte/";
                        parametros.put("SUBREPORT_DIR", pathReporte);
                        Reporte reporteController = new Reporte(parametros, "rptReciboIndividual.jasper");
                        reporteController.mostrarReportePdf();
                    } else {
                        Map parametros = new HashMap();
                        parametros.put("pnvCodigo", dni.getText());
                        String pathReporte = System.getProperty("user.dir") + "/src/pe/sigmas/reporte/";
                        parametros.put("SUBREPORT_DIR", pathReporte);
                        Reporte reporteController = new Reporte(parametros, "rptReciboIndividual.jasper");
                        reporteController.mostrarReportePdf();
                    }

                } else {
                    JOptionPane.showInternalMessageDialog(this, "El Contribuyente con el numero de DNI :" + dni.getText() + " no Existe.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showInternalMessageDialog(this, "Ingrese los datos necesarios para proceder con el calculo", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            System.out.println("ocurrio un error" + ex.getMessage());
        }
    }//GEN-LAST:event_individualActionPerformed

    private void actualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualActionPerformed
        // TODO add your handling code here:
        if (actual.isSelected()) {
            general.setSelected(false);
            actual.setSelected(true);
        } else {
            actual.setSelected(false);
            general.setSelected(true);
        }
    }//GEN-LAST:event_actualActionPerformed

    private void generalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalActionPerformed
        // TODO add your handling code here:
        if (general.isSelected()) {
            actual.setSelected(false);
            general.setSelected(true);
        } else {
            general.setSelected(false);
            actual.setSelected(true);
        }
    }//GEN-LAST:event_generalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox actual;
    private javax.swing.JTextField dni;
    private javax.swing.JCheckBox general;
    private javax.swing.JButton individual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private void limpiarControles() {
        dni.setText("");
        actual.setSelected(true);
    }
}
