/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.sigmas.presentacion;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pe.sigmas.entity.regcontribuyenteBean;
import pe.sigmas.entity.regobligacionBean;
import pe.sigmas.entity.vencimientoBean;
import pe.sigmas.logica.regcontribuyenteBL;
import pe.sigmas.logica.regobligacionBL;
import pe.sigmas.logica.vencimientoBL;
import pe.sigmas.util.Generic;
import pe.sigmas.util.validator;

/**
 *
 * @author Elle Lawliet
 */
public class frmgenerarDeudaIndividual extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmgenerarDeudaIndividual
     */
    HashMap<Integer, vencimientoBean> mapaDesde;
    HashMap<Integer, vencimientoBean> mapaHasta;

    public frmgenerarDeudaIndividual() {
        initComponents();
        mapaDesde = new HashMap<>();
        mapaHasta = new HashMap<>();
        cargarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        observacion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dni = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        desde = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        hasta = new javax.swing.JComboBox();
        actual = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        individual = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("GENERACION DE DEUDA POR USUARIO");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("CALCULO INDIVIDUAL DE DEUDA"));

        observacion.setColumns(20);
        observacion.setRows(5);
        observacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                observacionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(observacion);

        jLabel1.setText("Observacion:");

        jLabel2.setText("DNI Contribuyente");

        jLabel3.setText("Vencimiento");

        jLabel4.setText("Desde");

        desde.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        desde.setEnabled(false);

        jLabel5.setText("Hasta");

        hasta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        hasta.setEnabled(false);

        actual.setSelected(true);
        actual.setText("Actual?");
        actual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/sigmas/files/01_lblBuscar.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desde, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hasta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(actual))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(actual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(desde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(hasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        individual.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        individual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/sigmas/files/01_btnCalcDeuda.png"))); // NOI18N
        individual.setText("Calcular Deuda");
        individual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                individualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(individual)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(individual)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void individualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_individualActionPerformed
        // TODO add your handling code here:
        regobligacionBean oregobligacionBean = new regobligacionBean();
        try {
            if (!dni.getText().isEmpty() && !observacion.getText().isEmpty() && dni.getText().length() >= 8) {
                regcontribuyenteBean oregcontribuyenteBean = new regcontribuyenteBean();
                oregcontribuyenteBean.setIOps(3);
                  if (!validator.validarInteger(dni.getText())) {
                    JOptionPane.showInternalMessageDialog(this, "Numero de Documento Inocrrecto", "ERROR", JOptionPane.ERROR_MESSAGE);
                    dni.selectAll();
                    dni.requestFocus();
                    return;
                }
                oregcontribuyenteBean.setCCodRegContribuyente(dni.getText());
                oregcontribuyenteBean = Generic.getInstance(regcontribuyenteBL.class).fnGetregcontribuyenteBean(oregcontribuyenteBean);

                if (oregcontribuyenteBean != null) {
                    if (actual.isSelected()) {
                        oregobligacionBean.setIOps(2);
                    } else {
                        oregobligacionBean.setIOps(3);
                        int id1 = ((vencimientoBean) desde.getSelectedItem()).getIIdVencimiento();
                        int id2 = ((vencimientoBean) hasta.getSelectedItem()).getIIdVencimiento();
                        if (id1 >= id2) {
                            JOptionPane.showInternalMessageDialog(this, "Vencimiento Incorrectamente Seleccionado ", "Error", JOptionPane.WARNING_MESSAGE);
                            return;
                        }
                        oregobligacionBean.setBiIdRegObligacion(id1);
                        oregobligacionBean.setIIdVencimiento(id2);
                    }
                    oregobligacionBean.setCCodRegContribuyente(dni.getText());
                    oregobligacionBean.setNvObservacion(observacion.getText());
                    oregobligacionBean.setIIdRegUsuaRegistra(frminicio.IdUsuario);

                    boolean result = Generic.getInstance(regobligacionBL.class).fnInsertarregobligacionBean(oregobligacionBean);
                    if (result) {
                        limpiarControles();
                        JOptionPane.showInternalMessageDialog(this, "Generacion de deuda individual correcta.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showInternalMessageDialog(this, "Ocurrio error al generar deuda individual", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showInternalMessageDialog(this, "El Contribuyente con el numero de DNI :" + dni.getText() + " no Existe.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showInternalMessageDialog(this, "Ingrese los datos necesarios para proceder con el calculo", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            System.out.println("ocurrio un error");
        }
    }//GEN-LAST:event_individualActionPerformed

    private void actualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualActionPerformed
        // TODO add your handling code here:
        if (actual.isSelected()) {
            desde.setEnabled(false);
            hasta.setEnabled(false);
        } else {
            desde.setEnabled(true);
            hasta.setEnabled(true);
        }
    }//GEN-LAST:event_actualActionPerformed

    private void observacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_observacionKeyTyped
        // TODO add your handling code here:
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_observacionKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox actual;
    private javax.swing.JComboBox desde;
    private javax.swing.JTextField dni;
    private javax.swing.JComboBox hasta;
    private javax.swing.JButton individual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea observacion;
    // End of variables declaration//GEN-END:variables

    private void cargarCombo() {
        try {
            desde.removeAllItems();
            hasta.removeAllItems();
            vencimientoBean ovencimientoBean = new vencimientoBean();
            ovencimientoBean.setIOps(2);
            ArrayList<vencimientoBean> lista = Generic.getInstance(vencimientoBL.class).fnAutocompletevencimientoBean(ovencimientoBean);

            for (vencimientoBean v : lista) {
                desde.addItem(v);
                hasta.addItem(v);
                mapaDesde.put(v.getIIdVencimiento(), v);
                mapaHasta.put(v.getIIdVencimiento(), v);
            }
        } catch (Exception ex) {
            Logger.getLogger(frmgenerarDeudaIndividual.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void limpiarControles() {
        observacion.setText("");
        dni.setText("");
        desde.setSelectedIndex(0);
        hasta.setSelectedIndex(0);
        actual.setSelected(true);
        desde.setEnabled(false);
        hasta.setEnabled(false);
    }
}
