/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.sigmas.presentacion;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableColumnModel;
import pe.sigmas.entity.regtrabajadorBean;
import pe.sigmas.logica.regtrabajadorBL;
import pe.sigmas.util.Generic;
import pe.sigmas.util.GenericEstiloTabla;
import pe.sigmas.util.GenericTableModel;

/**
 *
 * @author Elle Lawliet
 */
public class frmListTrabajador extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmListTrabajador
     */
    GenericTableModel modeloTabla;
    TableColumnModel modeloColumna;
    String[] columnanes = {"ID", "NUM DOCUMENTO", "RAZON SOCIAL"};
    boolean[] editable = {false, false, false};
    boolean[] columnCheck = {false, false, false};

    public frmListTrabajador() {
        initComponents();
        modeloTabla = new GenericTableModel(columnanes, columnCheck, editable);
        jTable1.setModel(modeloTabla);
        modeloColumna = jTable1.getColumnModel();
        try {
            iniciarGrilla(7);
            ajustarColumna();
            estiloTabla();
            hideColumnTable();

        } catch (Exception ex) {
            Logger.getLogger(frmAdministrarUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txtBuscarTrabajador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setIconifiable(true);
        setMaximizable(true);
        setTitle("BUSQUEDA DE TRABAJADOR");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Trabajador"));
        jPanel3.setLayout(new java.awt.BorderLayout());

        txtBuscarTrabajador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarTrabajadorMouseClicked(evt);
            }
        });
        txtBuscarTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarTrabajadorActionPerformed(evt);
            }
        });
        txtBuscarTrabajador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarTrabajadorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarTrabajadorKeyTyped(evt);
            }
        });
        jPanel3.add(txtBuscarTrabajador, java.awt.BorderLayout.CENTER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/sigmas/files/01_lblBuscar.png"))); // NOI18N
        jPanel3.add(jLabel1, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarTrabajadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarTrabajadorKeyTyped
        // TODO add your handling code here:
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_txtBuscarTrabajadorKeyTyped

    private void txtBuscarTrabajadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarTrabajadorKeyReleased
        // TODO add your handling code here:
         if (txtBuscarTrabajador.isEditable()) {
            if (evt.getKeyCode() == 40) {
                if (modeloTabla.getRowCount() > 0) {
                    jTable1.setRowSelectionInterval(0, 0);
                    jTable1.requestFocus();                                    
                }
            } else {
                try {
                    iniciarGrilla(8);
                } catch (Exception ex) {
                    Logger.getLogger(frmAdministrarUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        }
    }//GEN-LAST:event_txtBuscarTrabajadorKeyReleased

    private void txtBuscarTrabajadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarTrabajadorMouseClicked
        // TODO add your handling code here:
        txtBuscarTrabajador.selectAll();
    }//GEN-LAST:event_txtBuscarTrabajadorMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            if (modeloTabla.getRowCount() > 0) {
                int index = jTable1.getSelectedRow();
                if (index > -1) {
                    try {

                        String codigo = modeloTabla.getValueAt(index, 0).toString();
                        String nombre = modeloTabla.getValueAt(index, 2).toString();
                        frmAdministrarUser.GetTrabajador(codigo, nombre);
                        this.dispose();
                    } catch (Exception ex) {
                        Logger.getLogger(frmAdministrarUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }

            }
            // do some action
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtBuscarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarTrabajadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarTrabajadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBuscarTrabajador;
    // End of variables declaration//GEN-END:variables
private void iniciarGrilla(int i) throws Exception {
        deleteRows();
        regtrabajadorBean oregtrabajadorBean = new regtrabajadorBean();
        oregtrabajadorBean.setIOps(i);
        oregtrabajadorBean.setBEstado(true);
        oregtrabajadorBean.setNvObservacion(txtBuscarTrabajador.getText());
        List lista = Generic.getInstance(regtrabajadorBL.class).fnGetListregtrabajadorBean(oregtrabajadorBean);
        lista.stream().forEach((list) -> {
            modeloTabla.addRow((Object[]) list);
        });
    }

    private void estiloTabla() {
        for (int i = 0; i < modeloColumna.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setHeaderRenderer(new GenericEstiloTabla());
        }
    }

    private void hideColumnTable() {
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
    }

    private void ajustarColumna() {
        modeloColumna.getColumn(0).setPreferredWidth(0);
        modeloColumna.getColumn(1).setPreferredWidth(50);
        modeloColumna.getColumn(2).setPreferredWidth(200);

    }

    private void deleteRows() {
        while (modeloTabla.getRowCount() > 0) {
            modeloTabla.removeRow(0);
        }
    }

}
