/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pe.sigmas.presentacion;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import pe.sigmas.util.Reporte;

/**
 *
 * @author Core i7
 */
public class frmReportePuntuales extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmReportePuntuales
     */
    public frmReportePuntuales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ejerciciopuntuales = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcmespuntuales = new javax.swing.JComboBox();
        jbReportePuntuales = new javax.swing.JButton();
        jBSalirPuntuales = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuarios Puntuales"));

        jLabel1.setText("Ejercicio :");

        jLabel2.setText("Mes :");

        jcmespuntuales.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));

        jbReportePuntuales.setText("Reporte");
        jbReportePuntuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbReportePuntualesActionPerformed(evt);
            }
        });

        jBSalirPuntuales.setText("Salir");
        jBSalirPuntuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirPuntualesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(ejerciciopuntuales, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jcmespuntuales, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jbReportePuntuales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBSalirPuntuales)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ejerciciopuntuales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jcmespuntuales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbReportePuntuales)
                    .addComponent(jBSalirPuntuales))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbReportePuntualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbReportePuntualesActionPerformed
        // TODO add your handling code here:
           int mes=0;
        String tipo=null;
        try
            {
             int ejercicio=Integer.parseInt(ejerciciopuntuales.getText());
             tipo=jcmespuntuales.getSelectedItem().toString();
             mes=obtenermes(tipo);
              Map parametros = new HashMap();
            //String pathReporte = System.getProperty("user.dir") + "/src/pe/sigmas/reporte/";
            //parametros.put("SUBREPORT_DIR", pathReporte);
            parametros.put("ejerciciop", ejercicio);
            parametros.put("mesp", mes);
            Reporte reporteController = new Reporte(parametros, "rptReportePuntuales.jasper");
            reporteController.mostrarReportePdf();
            
            System.out.println("SI  LLEGA HASTA AQUI");
                  
            }
    	 catch (NumberFormatException nfe){
             
	JOptionPane.showInternalMessageDialog(this, "Ingrese la Mora", "Error", JOptionPane.ERROR_MESSAGE);	
	}
            
    }//GEN-LAST:event_jbReportePuntualesActionPerformed

    private void jBSalirPuntualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirPuntualesActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_jBSalirPuntualesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ejerciciopuntuales;
    private javax.swing.JButton jBSalirPuntuales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbReportePuntuales;
    private javax.swing.JComboBox jcmespuntuales;
    // End of variables declaration//GEN-END:variables
public int obtenermes(String tipo)
       {
	int nummes=0;
          if(tipo.equals("Enero"))
                 {
                    nummes=1; 
                 }
             if(tipo.equals("Febrero"))
                 {
                    nummes=2; 
                 }
              if(tipo.equals("Marzo"))
                 {
                    nummes=3; 
                 }
              if(tipo.equals("Abril"))
                 {
                    nummes=4; 
                 }
               if(tipo.equals("Mayo"))
                 {
                    nummes=5; 
                 }
              if(tipo.equals("Junio"))
                 {
                    nummes=6; 
                 }
              if(tipo.equals("Julio"))
                 {
                    nummes=7; 
                 }
               if(tipo.equals("Agosto"))
                 {
                    nummes=8; 
                 }
                if(tipo.equals("Setiembre"))
                 {
                    nummes=9; 
                 }
                 if(tipo.equals("Octubre"))
                 {
                    nummes=10; 
                 }
                  if(tipo.equals("Noviembre"))
                 {
                    nummes=11; 
                 }
                   if(tipo.equals("Diciembre"))
                 {
                    nummes=12; 
                 }
              return nummes;
	} 
}
