/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pe.sigmas.presentacion;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import pe.sigmas.util.Reporte;

/**
 *
 * @author Core i7
 */
public class frmReporteMorosos extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmReporteMorosos
     */
    public frmReporteMorosos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tejerciciomoroso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcmesmoroso = new javax.swing.JComboBox();
        jbReporteMorosos = new javax.swing.JButton();
        jBSalirMorosidad = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Reporte"));

        jLabel1.setText("Ejercicio :");

        tejerciciomoroso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tejerciciomorosoActionPerformed(evt);
            }
        });

        jLabel2.setText("Vencimiento :");

        jcmesmoroso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));

        jbReporteMorosos.setText("Reporte");
        jbReporteMorosos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbReporteMorososActionPerformed(evt);
            }
        });

        jBSalirMorosidad.setText("Salir");
        jBSalirMorosidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirMorosidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tejerciciomoroso, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jcmesmoroso, 0, 121, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jbReporteMorosos)
                .addGap(18, 18, 18)
                .addComponent(jBSalirMorosidad)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tejerciciomoroso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jcmesmoroso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbReporteMorosos)
                    .addComponent(jBSalirMorosidad))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tejerciciomorosoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tejerciciomorosoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tejerciciomorosoActionPerformed

    private void jbReporteMorososActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbReporteMorososActionPerformed
        int mes=0;
        String tipo=null;
        try
            {
             int ejercicio=Integer.parseInt(tejerciciomoroso.getText());
             tipo=jcmesmoroso.getSelectedItem().toString();
            mes=obtenermes(tipo);
              Map parametros = new HashMap();
            //String pathReporte = System.getProperty("user.dir") + "/src/pe/sigmas/reporte/";
            //parametros.put("SUBREPORT_DIR", pathReporte);
            parametros.put("ejerciciom", ejercicio);
            parametros.put("mesm", mes);
            Reporte reporteController = new Reporte(parametros, "rptmorosos.jasper");
            reporteController.mostrarReportePdf();
                  
            }
    	 catch (NumberFormatException nfe){
             
	JOptionPane.showInternalMessageDialog(this, "Ingrese la Mora", "Error", JOptionPane.ERROR_MESSAGE);	
	}
            
    
        
    }//GEN-LAST:event_jbReporteMorososActionPerformed

    private void jBSalirMorosidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirMorosidadActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBSalirMorosidadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSalirMorosidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbReporteMorosos;
    private javax.swing.JComboBox jcmesmoroso;
    private javax.swing.JTextField tejerciciomoroso;
    // End of variables declaration//GEN-END:variables
public int obtenermes(String tipo)
       {
	int nummes=0;
          if(tipo.equals("Enero"))
                 {
                    nummes=1; 
                 }
             if(tipo.equals("Febrero"))
                 {
                    nummes=2; 
                 }
              if(tipo.equals("Marzo"))
                 {
                    nummes=3; 
                 }
              if(tipo.equals("Abril"))
                 {
                    nummes=4; 
                 }
               if(tipo.equals("Mayo"))
                 {
                    nummes=5; 
                 }
              if(tipo.equals("Junio"))
                 {
                    nummes=6; 
                 }
              if(tipo.equals("Julio"))
                 {
                    nummes=7; 
                 }
               if(tipo.equals("Agosto"))
                 {
                    nummes=8; 
                 }
                if(tipo.equals("Setiembre"))
                 {
                    nummes=9; 
                 }
                 if(tipo.equals("Octubre"))
                 {
                    nummes=10; 
                 }
                  if(tipo.equals("Noviembre"))
                 {
                    nummes=11; 
                 }
                   if(tipo.equals("Diciembre"))
                 {
                    nummes=12; 
                 }
              return nummes;
	} 
}
